default_stages: [ pre-commit ]
repos:
  - repo: local
    hooks:
      - id: makefile-command
        name: Rust Format
        entry: make format-check
        language: system
      - id: makefile-command
        name: Rust Check
        entry: make check
        language: system
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: check-merge-conflict
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.1
    hooks:
      - id: ruff
        args: ["--config", "synpy/pyproject.toml", "--fix"]
        files: ^synpy/
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.6.1
    hooks:
      - id: mypy
        args: ["--config-file", "synpy/pyproject.toml"]
        files: ^synpy/