[package]
name = "syn"
version = "0.1.0"
edition = "2021"

[dependencies]
bitvec = "1.0.1"
itertools = "0.13.0"
petgraph = { git = "https://github.com/daehiff/petgraph.git", rev = "4b700d7e188f973770a61a492892d61372ea7f9e", features = ["stable_graph"]}
typenum = "1.17.0"

[dev-dependencies]
criterion = "0.5.1"
rand = "0.9.0"

[[bench]]
name = "clifford_tableau"
harness = false
