# encoding: utf-8
# module synpy_core.synpy_rust

from typing import Any

def synthesize_pauli_exponential(*args: Any, **kwargs: Any) -> Any: ...

class PyCommand(object):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __new__(*args: Any, **kwargs: Any) -> Any: ...
    CX: Any
    CZ: Any
    H: Any
    Rx: Any
    Ry: Any
    Rz: Any
    S: Any
    SDgr: Any
    V: Any
    VDgr: Any
    X: Any
    Y: Any
    Z: Any

class PyPauliString(object):
    def as_tuple(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_qubits(self, *args: Any, **kwargs: Any) -> Any: ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __new__(*args: Any, **kwargs: Any) -> Any: ...

class PyCliffordTableau(object):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __new__(*args: Any, **kwargs: Any) -> Any: ...
    @classmethod
    def from_parts(cls, *args: Any, **kwargs: Any) -> Any: ...
    def synthesize(self, *args: Any, **kwargs: Any) -> Any: ...
    def size(self, *args: Any, **kwargs: Any) -> Any: ...
    def compose(self, *args: Any, **kwargs: Any) -> Any: ...

class PyPauliExponential(object):
    def add_cx(self, *args: Any, **kwargs: Any) -> Any: ...
    def add_h(self, *args: Any, **kwargs: Any) -> Any: ...
    def add_rz(self, *args: Any, **kwargs: Any) -> Any: ...
    def synthesize_to_qiskit(self, *args: Any, **kwargs: Any) -> Any: ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __new__(*args: Any, **kwargs: Any) -> Any: ...

class QiskitSynIR(object):
    def s(self, *args: Any, **kwargs: Any) -> Any: ...
    def v(self, *args: Any, **kwargs: Any) -> Any: ...
    def s_dgr(self, *args: Any, **kwargs: Any) -> Any: ...
    def v_dgr(self, *args: Any, **kwargs: Any) -> Any: ...
    def x(self, *args: Any, **kwargs: Any) -> Any: ...
    def y(self, *args: Any, **kwargs: Any) -> Any: ...
    def z(self, *args: Any, **kwargs: Any) -> Any: ...
    def h(self, *args: Any, **kwargs: Any) -> Any: ...
    def cx(self, *args: Any, **kwargs: Any) -> Any: ...
    def cz(self, *args: Any, **kwargs: Any) -> Any: ...
    def rx(self, *args: Any, **kwargs: Any) -> Any: ...
    def ry(self, *args: Any, **kwargs: Any) -> Any: ...
    def rz(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_circuit(self, *args: Any, **kwargs: Any) -> Any: ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __new__(*args: Any, **kwargs: Any) -> Any: ...
    def get_permutation(self) -> Any: ...

__all__ = [
    "PyCliffordTableau",
    "PyPauliString",
    "PyCommand",
    "synthesize_pauli_exponential",
    "PyPauliExponential",
    "QiskitSynIR",
]

__loader__: Any = ...
__spec__: Any = ...
